### ISSUE TITLE
Error with Firefox

### ISSUE THREAD

**Issue by BrandonEm** [rafpyprog/Mobilenium#8]
When I am trying to run the example, after I have installed all de dependencies I get this error:
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

I suppose it is for:  mobidriver.Firefox(browsermob_binary = browsermob_path)

But it is suppose to be using browsermob

**Comment by rafpyprog** [comment]
@BrandonEm ,

You need to install the driver for Firefox: https://selenium-python.readthedocs.io/installation.html#drivers
